server:
  ssl:
    key-store: classpath:keys/springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/postgres

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
