-- Инициализация

CREATE TABLE accounts
(
    id     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    number text UNIQUE,
    client text,
    amount numeric
);

INSERT INTO accounts
VALUES (1, '1001', 'alice', 1000.00),
       (2, '2001', 'bob', 100.00),
       (3, '2002', 'bob', 900.00);

DROP TABLE accounts;

