
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/postgres

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8085
