spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/postgres

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
