version: "3"
services:
  postgres:
    image: "postgres:13.4-alpine"
    container_name: "demo-postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "35432:5432"
    volumes:
      - "./dev-env/postgres/init.sql:/docker-entrypoint-initdb.d/1-init.sql"

  elastic:
    image: elasticsearch:7.17.9
    container_name: demo-elastic
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: demo-kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://demo-elastic:9200
    depends_on:
      - elastic
